export const GET_WORKORDERS_BY_SITE = 'GET_WORKORDERS_BY_SITE';
export const SITE_GROUP_INFO = 'SITE_GROUP_INFO';
export const SET_INNER_DOUGHNUT = 'SET_INNER_DOUGHNUT';
export const SET_OUTER_DOUGHNUT = 'SET_OUTER_DOUGHNUT';
export const SET_LOADING = 'SET_LOADING';
